### ISSUE TITLE
Apostrophe in title occasionally breaks search

### ISSUE THREAD

**Issue by chocolatechipcats** [sharkusmanch/playnite-pcgamingwiki-metadata-provider#40] opened 2022-12-25 23:40 UTC
Possibly related: #28 

Steps to replicate:

1. Create a game with title `Sid Meier's Civilization II`. 
2. Use Download Metadata > PCGamingWiki. Zero results.
3. Remove `Sid Meier's` from the search. The first result is... Sid Meier's Civilization II.

I can also replicate this with `Sid Meier's Railroads!` and `Sid Meier's Alpha Centauri`.

This does not always occur; `Assassin's Creed` got results as expected. Perhaps the search has something against Sid Meier.

**Comment by sharkusmanch** [comment] 2023-01-27 05:02
Was able to reproduce this with the games mentioned. Similar issue with `Hi-Fi Rush`

**Comment by Acru** [comment] 2023-05-25 23:20
Oh dear, I came about this issue as well and am sad to see its been known a while with no fix.
Lets see if we can correct that.  Though there seems to be no pattern to affected titles?
[I did notice that replacing the apostrophe with a double quote (") causes the search to work for most titles, though not all.]

Affected: [Based on batch results - some titles may just not be in PCGW's database]
	Line 6: "8Doors: Arum's Afterlife Adventure"
	Line 7: "A Mortician's Tale"
	Line 8: "Alan Wake's American Nightmare"
	Line 9: "Alder's Blood Prologue"
	Line 30: "Broken Sword: Director's Cut"
	Line 48: "Discovery Tour by Assassin's Creed: Ancient Egypt"
	Line 58: "Fiendish Freddy's Big Top o' Fun"
	Line 73: "High Sidin': Hyphy Edition"
	Line 84: "Ken Follett's The Pillars of the Earth"
	Line 88: "King Arthur's Gold"
	Line 89: "LEGO Builder's Journey"
	Line 92: "Lone Survivor: The Director's Cut"
	Line 112: "No Man's Sky"
	Line 114: "Oddworld: Abe's Oddysee"
	Line 115: "Ollie & Bollie's Outdoor Estate"
	Line 123: "Penny Arcade's On the Rain-Slick Precipice of Darkness 3"
	Line 124: "Penny Arcade's On the Rain-Slick Precipice of Darkness 4"
	Line 131: "Q.U.B.E.: Director's Cut"
	Line 135: "Recettear: An Item Shop's Tale"
	Line 138: "Retired Men's Nude Beach Volleyball"
	Line 171: "Shadowrun: Dragonfall - Director's Cut"
	Line 173: "Shantae and the Pirate's Curse"
	Line 174: "Shantae: Risky's Revenge - Director's Cut"
	Line 177: "Sid Meier's Civilization III: Complete"
	Line 178: "Sid Meier's Civilization VI"
	Line 204: "Super Lucky's Tale"
	Line 211: "Teenage Mutant Ninja Turtles: Shredder's Revenge"
	Line 212: "The Beginner's Guide"
	Line 215: "The Lion's Song"
	Line 223: "Tiny and Big: Grandpa's Leftovers"
	Line 224: "Tiny Tina's Assault on Dragon Keep: A Wonderlands One-shot Adventure"
	Line 226: "Tom Clancy's Ghost Recon"
	Line 227: "Tom Clancy's Ghost Recon Wildlands"
	Line 228: "Tom Clancy's Splinter Cell Chaos Theory"
	Line 241: "Viscera Cleanup Detail: Santa's Rampage"

Not Affected:
	Line 64: "Alwa's Awakening"
	Line 93: "Assassin's Creed"
	Line 94: "Assassin's Creed II"
	Line 95: "Assassin's Creed III"
	Line 96: "Assassin's Creed Chronicles China"
	Line 97: "Assassin's Creed Syndicate"
	Line 98: "Assassin's Creed Unity"
	Line 289: "DEMON'S TILT"
	Line 316: "DON'T GIVE UP"
	Line 317: "Don't Starve"
	Line 318: "Don't Starve Together"
	Line 320: "Doomdark's Revenge"
	Line 436: "Garry's Mod"
	Line 458: "God's Trigger"
	Line 495: "Hack 'n' Slash"
	Line 525: "Hero's Hour"
	Line 616: "King's Quest"
	Line 653: "Lovecraft's Untold Stories"
	Line 673: "Marie's Room"
	Line 697: "Mirror's Edge"
	Line 703: "Montague's Mount"
	Line 748: "Oddworld: New 'n' Tasty"
	Line 936: "Shu's Garden"
	Line 1050: "Telltale Texas Hold'Em"
	Line 1129: "Them's Fightin' Herds"
	Line 1248: "Wilmot's Warehouse"
	Line 1267: "Yoku's Island Express"

**Comment by Acru** [comment] 2023-05-27 04:47
Some more things I noticed;

For just about any symbol or space, you can replace it by any number of symbols (!@#$%^&*;: and others) or spaces and the search will still work, implying that the api is treating any such sequence as a single whitespace.

For the apostrophe games that are found successfully, there can be any number of spaces or symbols instead of an apostrophe (or any other space or symbol), and the name is still found.

For the apostrophe games that are not found in a search, however, the search will only work if there is a quotation mark somewhere before where the apostrophe appears.

Eg:
> Alan"Wake s American Nightmare
will be found when manually searching with the plugin, but;
> Alan Wake s American"Nightmare
will not.

There is something different about the PCGW data of just these unmatched games that is messing up the search, and I am guessing that the apostrophe is directly stored instead of a whitespace marker (an underscore) , but in any case it may be simplest to fix by internally quoting all searches;
> "Alan Wake's American Nightmare"
which seems to work in all cases that I tested, and it found more matches in general, for some titles.

**Comment by Acru** [comment] 2023-05-27 10:30
I tried implementing this myself, changing the uses of `client.SearchGames(X)` to `client.SearchGames("\"" + X + "\"")` and it seems to work. Would probably have issues if the name itself happens to use quotation marks though, and as such internal quotes should be replaced by spaces.  Will test further.

**Comment by Acru** [comment] 2023-05-27 12:31
Removing all the quotes also allowed `Sorcery! Parts 1 & 2` to match to `Sorcery! Parts 1 and 2`, perhaps PCGW changed things on their end so quotes aren't needed anymore?

**Comment by sharkusmanch** [comment] 2023-05-28 03:01
Thanks for taking a look! I will try to set aside some time this week to dig more into this.

Yea, I originally add that quoting to resolve https://github.com/sharkusmanch/playnite-pcgamingwiki-metadata-provider/issues/28

**Comment by Acru** [comment] 2023-05-29 09:39
> Yea, I originally add that quoting to resolve #28

I tried searching `The Signal from Tölva` in my quotes-removed build and it didn't find a match, though I did notice something rather odd...

Editing the search to `The Signal from` also finds nothing where it ought to work, but searching for `The Signal Tölva` or even just `Tölva` finds the correct match, despite the accented character.

**Comment by Acru** [comment] 2023-05-30 03:26
More info from when I was manually matching some 70 games with editions;

`Death Ray Manta SE`, `Fallout: New Vegas - Ultimate Edition`, and `Jotun: Valhalla Edition` won't match unless within quotes, though no nonascii characters are involved, and `Lone Survivor: The Director's Cut` won't match with or without quotes as it includes an apostrophe, though will match from `Lone Survivor: The Director`

**Comment by Acru** [comment] 2023-05-30 08:55
Here is an odd one which I have a feeling might be a clue pointing to the issue, searching `"Tiny and Big: Grandpa'` matches to `Tiny and Big: Grandpa's Leftovers` but the metadata comes back as `Tiny &amp; Big in Grandpa&#039;s Leftovers` (with the literal codes), where searching `Tiny & Big: Grandpa's Leftovers` returns `Tiny & Big in Grandpa's Leftovers` and metadata without the codes.

**Comment by sharkusmanch** [comment] 2024-02-17 02:27
Fixed in v1.2.4

**Closed by sharkusmanch** 2024-02-17 02:26 UTC
Labels: bug
